name: Publish Swift Bindings
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LWK repo release (MAJOR.MINOR.PATCH)'
        required: true
        type: string
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VERSION: 0.7.0
      
jobs:
  build-tag-release:
    name: Build, tag, and release the Breez SDK Swift bindings
    runs-on: macos-14
    steps:

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@1.75.0
        with:
            targets: x86_64-apple-ios,aarch64-apple-ios,aarch64-apple-ios-sim
      - name: Setup just
        uses: extractions/setup-just@v1
        with:
            just-version: 1.5.0  # optional semver specification, otherwise latest
      - name: Checkout lwk repo
        uses: actions/checkout@v4
        with:
          repository: Blockstream/lwk
          path: build
          ref: $VERSION
      - name: Checkout lwk-swift repo
        uses: actions/checkout@v4

      - name: Build Swift bindings
        working-directory: build
        run: just swift
      - name: Compress XCFramework
        working-directory: build
        run: |
          zip -9 -r target/lwkFFI.xcframework.zip lwkFFI.xcframework
          echo "XCF_CHECKSUM=`swift package compute-checksum lwkFFI.xcframework.zip`" >> $GITHUB_ENV
      - name: Update Swift Package definition
        run: |
          sed -i '' 's#.binaryTarget(name: "lwkFFI",*$#.binaryTarget(name: "lwkFFI", url: "https://github.com/Blockstream/lwk-swift/releases/download/${{ inputs.version }}/lwkFFI.xcframework.zip", checksum: "${{ env.XCF_CHECKSUM }}"),#' Package.swift
      - name: Update Cocoapods definitions
        working-directory: dist
        run: |
          sed -i '' 's#^.\{2\}spec.version.*$#  spec.version                = "$VERSION"#' lwkFFI.podspec
          sed -i '' 's#^.\{2\}spec.version.*$#  spec.version                = "$VERSION"#' LiquidWalletKit.podspec
      - name: Tag the Swift bindings
        run: |
          git add Package.swift
          git add Sources
          git add lwkFFI.podspec
          git add LiquidWalletKit.podspec
          git commit -m "Bump Liquid Wallet Kit to version $VERSION"
          git push
          git tag $VERSION -m "$VERSION"
          git push --tags
      - name: Release and attach XCFramework binary artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/sdk-bindings/bindings-swift/breez_sdkFFI.xcframework.zip"
          tag: $VERSION
          token: ${{ secrets.GITHUB_TOKEN }}
          name: $VERSION
          prerelease: true
      - name: Push update to Cocoapods trunk
        working-directory: dist
        env:
          COCOAPODS_TRUNK_TOKEN: ${{secrets.COCOAPODS_TRUNK_TOKEN}}
        run: |
          pod trunk push lwkFFI.podspec --allow-warnings
          pod trunk push LiquidWalletKit.podspec --allow-warnings --synchronous
